name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale by an automated process because it has not had any recent activity. It will be automatically closed in 14 days if no further activity occurs. If this is still an issue please add a new comment with more recent details and repro steps.'
        days-before-stale: 60
        days-before-close: 14